# Generated by Django 3.2.4 on 2021-06-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre')], default='male', max_length=10, verbose_name='Sexo'),
        ),
    ]
