# Generated by Django 3.2.4 on 2021-06-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_client_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='metodo',
            field=models.CharField(choices=[('CON', 'Contado'), ('CRE', 'Credito')], default='CON', max_length=10, verbose_name='Método de pago'),
        ),
    ]
