# Generated by Django 3.2.4 on 2021-06-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20210615_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='metodo',
            field=models.CharField(choices=[('CON', 'Contado'), ('CRE', 'Crédito')], default='CON', max_length=10, verbose_name='Método de pago'),
        ),
    ]
